import os.path
from py.scons.utils import *

Import('env', 'sources', 'node')

# add static simulation flag as there is no other
# hardware-implementation at the moment
env.AppendUnique(CPPDEFINES=['_SIM_'])

# determine compiler and linker flags for SDL
env.ParseConfig('sdl-config --cflags')
env.ParseConfig('sdl-config --libs')
env.Append(LIBS = ['SDL_image'])
env.AppendUnique(CPPPATH=['.'])

backend_sources =  env.Glob('*.c')
backend_objects = []

objs_lib = targets_from_src_list(sources['lib'], 'lib', env.Object)
node_dir = os.path.join('nodes', node)
objs_node = targets_from_src_list(sources['node'], node_dir, env.Object)
objs_backend = targets_from_src_list(backend_sources, 'backend', env.Object)

env.Program(target = node, source = objs_backend + objs_lib + objs_node)
