import os.path
from py.scons.utils import *

Import('env', 'sources', 'node')

cflags = {
  'DF_CPU': 16000000,
  'mmcu': 'atmega8'
  }

env['CC'] = 'avr-gcc'
env.AppendUnique(CPPPATH=['.'])
env.Append(CFLAGS=create_ext_opts_str(cflags))

bld = Builder(action = 'avr-objcopy -j .text -j .data -O ihex $SOURCE $TARGET',
        suffix = '.hex',
        src_suffix = '.elf')

env.Append(BUILDERS = {'Hex' : bld})

backend_sources =  env.Glob('*.c')
backend_objects = []

objs_lib = targets_from_src_list(sources['lib'], 'lib', env.Object)
objs_node = targets_from_src_list(sources['node'], 'nodes', env.Object)
objs_backend = targets_from_src_list(backend_sources, 'backend', env.Object)

node_elf = env.Program(target = node + '.elf', source = objs_backend + objs_lib + objs_node)
env.Hex(target = node + '.hex', source = node_elf)
